version: "3.9"

services:
  # Container definition for the devcontainer
  devcontainer:
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.11.6}
      target: dev
    stdin_open: true
    tty: true
    volumes:
      - .:/workspaces/pizza/

  # Container definition for running the production app image
  app:
    build:
      context: .
      target: app
    tty: true
    ports:
      - "8001:8000"
    volumes:
      - .:/workspaces/pizza/
    command: ["serve", "--dev"]

networks:
  default:
    name: pizza-network
